version: '3.8'

services:
  game-service:
    build: ./backend/game-service
    ports:
      - "8000:8000"

  user-service:
    build: ./backend/user-service
    ports:
      - "8002:8002"
    environment:
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - mongo

  ai-service:
    build: ./backend/ai-service
    ports:
      - "8003:8003"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - game-service
      - user-service
      - ai-service

volumes:
  mongo-data: