name: Backend CI

on:
  push:
    branches:
      - '*' # Declenche le workflow pour toutes les branches
  pull_request:
    branches: 
      - '*'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r backend/game-service/requirements.txt
        pip install -r backend/user-service/requirements.txt
    - name: Test with pytest
      run: |
        pytest --cov-report=xml
    - name: Create comment
      uses: peter-evans/create-or-update-comment@v4
      with:
        issue-number: 1
        body: |
          This is a multi-line test comment
          - With GitHub **Markdown** :sparkles:
          - Created by [create-or-update-comment][1]

          [1]: https://github.com/peter-evans/create-or-update-comment
        reactions: '+1'