name: CI on pull request

on:
  pull_request:
    branches: 
      - '*'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Récupère tout l'historique pour permettre la comparaison
        ref: ${{ github.head_ref }}  # Checkout de la branche source de la PR

    - name: Fetch target branch
      run: |
        git fetch origin ${{ github.base_ref }}  # Récupère la branche cible de la PR

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r backend/game-service/requirements.txt
        pip install -r backend/user-service/requirements.txt

    - name: Test with pytest
      run: |
        pytest --cov-report=xml

    - name: Check coverage for PR changes
      run: |
        diff-cover coverage.xml --compare-branch=origin/${{ github.base_ref }} --fail-under=60