name: CI

on:
  pull_request:
    branches: 
      - '*'
  push:
    branches:
      - 'main'
      - 'frontback'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.head_ref || github.ref_name }}

    - name: Fetch target branch of PR
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        git fetch origin ${{ github.base_ref }}  # Récupère la branche cible de la PR

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r backend/game-service/requirements.txt
        pip install -r backend/user-service/requirements.txt

    - name: Test with pytest
      run: |
        pytest --cov-report=xml

    - name: Check coverage for PR changes
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        diff-cover coverage.xml --compare-branch=origin/${{ github.base_ref }} --fail-under=60